### ISSUE TITLE
Error creating Driver class object

### ISSUE THREAD

**Issue by m0rg0t** [karlseguin/parse-dotnet#1]
Hello.

At this code:

ParseConfiguration.Configure(APPLICATION_ID, REST_API_KEY);
var parse = new Driver();

Get error Could not load type 'Parse.Driver' from assembly 'Parse, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

(Parse installed using NuGet).

**Comment by karlseguin** [comment]
I can reproduce it, but can't fix it. No idea and, to be honest, don't particularly care. This is something stupid in either .NET, nuget or myself.

If you get the source and build against that, it seems to work fine.

**Comment by m0rg0t** [comment]
Thank's, will build it manualy.

**Comment by m0rg0t** [comment]
> If you get the source and build against that, it seems to work fine.
> And is it possible to add working dll to repository?
